### ISSUE TITLE
Enquiry for wireless SoC info

### ISSUE THREAD

**Issue by huhanwj** [awsdocs/aws-deepracer-developer-guide#11]
I have gone through the AWS Developer Documentation but it doesn't have much technical information about the wireless hardware part as we may consider modify the wireless SoC driver to realize some customized functions.

So the question is can you provide the model of the Wireless SoC on the motherboard and the way that the Wi-Fi is integrated on the board (soldered or installed in a M.2 slot).

Many thanks to your kind help!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
