### ISSUE TITLE
Restore Failed

### ISSUE THREAD

**Issue by bz815** [awsdocs/aws-deepracer-developer-guide#12]
Hi,

I am having trouble enabling the ssh function using the console (still not sure why), so I tried to restore the deepracer to its factory setup by following the below two links

https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-vehicle-factory-reset-preparation.html
https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-vehicle-factory-reset-instructions.html

I am able to setup the boot flash drive by following the instructions, and I am pretty sure that I did it in the correct way. However, it directs me to the Ubuntu tryout page when I do "Boot from file", and it is not the same results as described in the link above. Now, I cannot boot up the car. 

Could you provide me some possible solution to this?

Thank you

PS: For the ssh option, I can successfully change the password in the console, and it even pops up a message saying that the ssh is enabled, but the actual status is still disabled. Any insight to this is appreciated.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
