### ISSUE TITLE
Any way to evaluate a downloaded model

### ISSUE THREAD

**Issue by sumitag** [awsdocs/aws-deepracer-developer-guide#3]
Is there any way to evaluate a downloaded model for the car using robomaker simulation.
I don't have all the sagemaker ckpt files.

**Comment by APratham** [comment]
Hi @sumitag, I wanted to know if your issue is resolved or you are still looking for help with evaluating. I can redirect you to resources which *may* help

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
