### ISSUE TITLE
Update documentation to include technical information

### ISSUE THREAD

**Issue by APratham** [awsdocs/aws-deepracer-developer-guide#7]
I have gone through AWS Developer Documentation but it doesn't have much technical information. I want to use DeepRacer for my project but for that I need diagrams, flowcharts and algorithm for the AWS DeepRacer. We are trying and generating as much as possible. I wanted to know whether I can be allowed to contribute them to this repo and to AWS official documentation once my project is completed. I am also willing to discuss more about this with AWS DeepRacer team so that our diagrams match the thoughts they had when designing the product. 

Kindly assign me this issue so I can begin working on the updates described. I will create a PR with changes as much as possible from my end.

Thanks a lot for considering my suggestion!

P.S: I don't mean the diagrams from the re:Invent presentation. They are enough for someone who is looking forward to using the car for racing, but we want it for a different purpose. If more clarification is needed, I will be more than happy to provide it

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
